productName: "eric-oss-network-assurance-search HELM"
productNumber: "CXD 101 415"
images:
  assurancesearch:
    productName: "eric-oss-network-assurance-search IMAGE"
    productNumber: "CXU 101 1693"
    registry: "REPO_URL"
    repoPath: REPO_PATH
    name: IMAGE_NAME
    tag: VERSION
  eric-api-gateway-client:
    productName: "eric-api-gateway-client"
    productNumber: "CXC 201 2331"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-eric-oss-drop"
    name: "eric-api-gateway-client"
    tag: "1.0.43-1"
