type: object
properties:
  logging:
    description: Settings for UI logging
    type: object
    properties:
      logLevel:
        description: Full name of an UI entity. Well-known name defined during development time
        type: string
        enum: [debug, info, warning, error, critical]
  routes:
    description: Optional definition of custom API routes
    type: object
    properties:
      internal:
        description: The internal API description
        type: object
        properties:
          prefix:
            type: string
          routes:
            type: object
      logging:
        description: The logging API description
        type: object
        properties:
          prefix:
            type: string
          routes:
            type: object
