{{- define "eric-oss-network-assurance-search.labels" }}
app.kubernetes.io/name: {{ template "eric-oss-network-assurance-search.name" . }}
app.kubernetes.io/version: {{ template "eric-oss-network-assurance-search.version" . }}
app.kubernetes.io/instance: {{ .Release.Name | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
helm.sh/chart: {{ include "eric-oss-network-assurance-search.chart" . }}
{{- end}}
