{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eric-oss-network-assurance-search.name" . }}-network-policy
  annotations:
      {{- include "eric-oss-network-assurance-search.commonAnnotations" . | nindent 4 }}
  labels:
    {{- include "eric-oss-network-assurance-search.labels" . | nindent 4 }}
    app: {{ .Chart.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-oss-network-assurance-search.name" . }}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-adp-gui-aggregator-service
    ports:
    - port: {{ include "eric-oss-network-assurance-search.service-port" . }}
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}
