apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-oss-network-assurance-search.name" . }}-psp-binding
  labels:
    {{- include "eric-oss-network-assurance-search.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-network-assurance-search.commonAnnotations" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "eric-oss-network-assurance-search.release.name" . }}-allowed-use-privileged-policy
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-oss-network-assurance-search.name" . }}-sa
