{{- if  (eq (include "eric-oss-network-assurance-search.nas-security-tls-enabled" .) "true") }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ include "eric-oss-network-assurance-search.name" . }}-se-client-cert
  labels:
    {{- include "eric-oss-network-assurance-search.helmK8s-labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-network-assurance-search.commonAnnotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-oss-network-assurance-search.name" . }}-se-client-cert-secret
  certificate:
    subject:
      cn: {{ include "eric-oss-network-assurance-search.name" . }}
    issuer:
      reference: eric-data-search-engine-http-ca-cert
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{ end }}
