version: 0.1
env:
  - name: UI_SERVICE_CONFIG
    value: $(volumeMounts:config-volume)
  - name: KUBERNETES_SERVICE_ACCOUNT
    value: $(volumeMounts:eric-oss-network-assurance-search-serviceaccount-token-*)
  - name: KUBERNETES_SERVICE_HOST
    value: $(services:kubernetes.default)
  - name: KUBERNETES_SERVICE_PORT
    value: 443
  - name: NODE_ENV
    value: bridge
