/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import ContextType from './ContextType.js';
import Entity from './Entity.js';

/**
 * The Context1 model module.
 * @module model/Context1
 * @version 1.0.0
 */
class Context1 {
  /**
   * Constructs a new <code>Context1</code>.
   * aggregation context
   * @alias module:model/Context1
   * @param type {module:model/ContextType}
   * @param contextFields {Array.<module:model/Entity>} aggregated entities in this context
   */
  constructor(type, contextFields) {
    Context1.initialize(this, type, contextFields);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, type, contextFields) {
    obj.type = type;
    obj.contextFields = contextFields;
  }

  /**
   * Constructs a <code>Context1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Context1} obj Optional instance to populate.
   * @return {module:model/Context1} The populated <code>Context1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Context1();

      if (Object.prototype.hasOwnProperty.call(data, 'id')) {
        obj.id = ApiClient.convertToType(data.id, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'name')) {
        obj.name = ApiClient.convertToType(data.name, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'type')) {
        obj.type = ContextType.constructFromObject(data.type);
      }
      if (Object.prototype.hasOwnProperty.call(data, 'contextFields')) {
        obj.contextFields = ApiClient.convertToType(data.contextFields, [Entity]);
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      id: this.id,
      name: this.name,
      type: this.type,
      contextFields: this.contextFields,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>Context1</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Context1</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of Context1.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          `The required field \`${property}\` is not found in the JSON data: ${JSON.stringify(
            data,
          )}`,
        );
      }
    }
    // ensure the json data is a string
    if (!Context1.jsonStringValidation(data, 'id')) {
      throw new Error(
        `Expected the field \`id\` to be a primitive type in the JSON string but got ${data.id}`,
      );
    }
    // ensure the json data is a string
    if (!Context1.jsonStringValidation(data, 'name')) {
      throw new Error(
        `Expected the field \`name\` to be a primitive type in the JSON string but got ${data.name}`,
      );
    }
    // validate the optional field `type`
    if (data.type) {
      // data not null
      ContextType.validateJSON(data.type);
    }
    if (data.contextFields) {
      // data not null
      // ensure the json data is an array
      if (!Array.isArray(data.contextFields)) {
        throw new Error(
          `Expected the field \`contextFields\` to be an array in the JSON data but got ${data.contextFields}`,
        );
      }
      // validate the optional field `contextFields` (array)
      for (const item of data.contextFields) {
        Entity.validateJSON(item);
      }
    }

    return true;
  }

  /**
   * Returns context instance ID
   * @return {String}
   */
  getId() {
    return this.id;
  }

  /**
   * Sets context instance ID
   * @param {String} id context instance ID
   */
  setId(id) {
    this.id = id;
  }

  /**
   * Returns name for the context
   * @return {String}
   */
  getName() {
    return this.name;
  }

  /**
   * Sets name for the context
   * @param {String} name name for the context
   */
  setName(name) {
    this.name = name;
  }

  /**
   * @return {module:model/ContextType}
   */
  getType() {
    return this.type;
  }

  /**
   * @param {module:model/ContextType} type
   */
  setType(type) {
    this.type = type;
  }

  /**
   * Returns aggregated entities in this context
   * @return {Array.<module:model/Entity>}
   */
  getContextFields() {
    return this.contextFields;
  }

  /**
   * Sets aggregated entities in this context
   * @param {Array.<module:model/Entity>} contextFields aggregated entities in this context
   */
  setContextFields(contextFields) {
    this.contextFields = contextFields;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ApiClient.convertToType(123456, 'String');
  }
}

Context1.RequiredProperties = ['type', 'contextFields'];

/**
 * context instance ID
 * @member {String} id
 */
Context1.prototype.id = undefined;

/**
 * name for the context
 * @member {String} name
 */
Context1.prototype.name = undefined;

/**
 * @member {module:model/ContextType} type
 */
Context1.prototype.type = undefined;

/**
 * aggregated entities in this context
 * @member {Array.<module:model/Entity>} contextFields
 */
Context1.prototype.contextFields = undefined;

export default Context1;
