/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import EntityFilterAllOf from './EntityFilterAllOf.js';
import EntityType from './EntityType.js';
import Filter from './Filter.js';

/**
 * The EntityFilter model module.
 * @module model/EntityFilter
 * @version 1.0.0
 */
class EntityFilter {
  /**
   * Constructs a new <code>EntityFilter</code>.
   * @alias module:model/EntityFilter
   * @implements module:model/Filter
   * @implements module:model/EntityFilterAllOf
   * @param type {module:model/EntityFilter.TypeEnum} filter type
   * @param entityType {module:model/EntityType}
   * @param searchPattern {String} substring match pattern for the resource name
   */
  constructor(type, entityType, searchPattern) {
    Filter.initialize(this);
    EntityFilterAllOf.initialize(this, type, entityType, searchPattern);
    EntityFilter.initialize(this, type, entityType, searchPattern);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, type, entityType, searchPattern) {
    obj.type = type;
    obj.entityType = entityType;
    obj.searchPattern = searchPattern;
  }

  /**
   * Constructs a <code>EntityFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EntityFilter} obj Optional instance to populate.
   * @return {module:model/EntityFilter} The populated <code>EntityFilter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EntityFilter();
      Filter.constructFromObject(data, obj);
      EntityFilterAllOf.constructFromObject(data, obj);

      if (Object.prototype.hasOwnProperty.call(data, 'name')) {
        obj.name = ApiClient.convertToType(data.name, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'not')) {
        obj.not = ApiClient.convertToType(data.not, 'Boolean');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'type')) {
        obj.type = ApiClient.convertToType(data.type, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'entityType')) {
        obj.entityType = EntityType.constructFromObject(data.entityType);
      }
      if (Object.prototype.hasOwnProperty.call(data, 'searchPattern')) {
        obj.searchPattern = ApiClient.convertToType(data.searchPattern, 'String');
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      name: this.name,
      not: this.not,
      type: this.type,
      entityType: this.entityType,
      searchPattern: this.searchPattern,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>EntityFilter</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EntityFilter</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of EntityFilter.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          `The required field \`${property}\` is not found in the JSON data: ${JSON.stringify(
            data,
          )}`,
        );
      }
    }
    // ensure the json data is a string
    if (!EntityFilter.jsonStringValidation(data, 'name')) {
      throw new Error(
        `Expected the field \`name\` to be a primitive type in the JSON string but got ${data.name}`,
      );
    }
    // ensure the json data is a string
    if (!EntityFilter.jsonStringValidation(data, 'type')) {
      throw new Error(
        `Expected the field \`type\` to be a primitive type in the JSON string but got ${data.type}`,
      );
    }
    // validate the optional field `entityType`
    if (data.entityType) {
      // data not null
      EntityType.validateJSON(data.entityType);
    }
    // ensure the json data is a string
    if (!EntityFilter.jsonStringValidation(data, 'searchPattern')) {
      throw new Error(
        `Expected the field \`searchPattern\` to be a primitive type in the JSON string but got ${data.searchPattern}`,
      );
    }

    return true;
  }

  /**
   * Returns name of the filter
   * @return {String}
   */
  getName() {
    return this.name;
  }

  /**
   * Sets name of the filter
   * @param {String} name name of the filter
   */
  setName(name) {
    this.name = name;
  }

  /**
   * Returns if true, inverses the filter
   * @return {Boolean}
   */
  getNot() {
    return this.not;
  }

  /**
   * Sets if true, inverses the filter
   * @param {Boolean} not if true, inverses the filter
   */
  setNot(not) {
    this.not = not;
  }

  /**
   * Returns filter type
   * @return {module:model/EntityFilter.TypeEnum}
   */
  getType() {
    return this.type;
  }

  /**
   * Sets filter type
   * @param {module:model/EntityFilter.TypeEnum} type filter type
   */
  setType(type) {
    this.type = type;
  }

  /**
   * @return {module:model/EntityType}
   */
  getEntityType() {
    return this.entityType;
  }

  /**
   * @param {module:model/EntityType} entityType
   */
  setEntityType(entityType) {
    this.entityType = entityType;
  }

  /**
   * Returns substring match pattern for the resource name
   * @return {String}
   */
  getSearchPattern() {
    return this.searchPattern;
  }

  /**
   * Sets substring match pattern for the resource name
   * @param {String} searchPattern substring match pattern for the resource name
   */
  setSearchPattern(searchPattern) {
    this.searchPattern = searchPattern;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ApiClient.convertToType(123456, 'String');
  }
}

EntityFilter.RequiredProperties = ['type', 'entityType', 'searchPattern'];

/**
 * name of the filter
 * @member {String} name
 */
EntityFilter.prototype.name = undefined;

/**
 * if true, inverses the filter
 * @member {Boolean} not
 * @default false
 */
EntityFilter.prototype.not = false;

/**
 * filter type
 * @member {module:model/EntityFilter.TypeEnum} type
 */
EntityFilter.prototype.type = undefined;

/**
 * @member {module:model/EntityType} entityType
 */
EntityFilter.prototype.entityType = undefined;

/**
 * substring match pattern for the resource name
 * @member {String} searchPattern
 */
EntityFilter.prototype.searchPattern = undefined;

// Implement Filter interface:
/**
 * name of the filter
 * @member {String} name
 */
Filter.prototype.name = undefined;
/**
 * if true, inverses the filter
 * @member {Boolean} not
 * @default false
 */
Filter.prototype.not = false;
// Implement EntityFilterAllOf interface:
/**
 * filter type
 * @member {module:model/EntityFilterAllOf.TypeEnum} type
 */
EntityFilterAllOf.prototype.type = undefined;
/**
 * @member {module:model/EntityType} entityType
 */
EntityFilterAllOf.prototype.entityType = undefined;
/**
 * substring match pattern for the resource name
 * @member {String} searchPattern
 */
EntityFilterAllOf.prototype.searchPattern = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
EntityFilter.TypeEnum = {
  /**
   * value: "entity"
   * @const
   */
  entity: 'entity',
};

export default EntityFilter;
