/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The Filter model module.
 * @module model/Filter
 * @version 1.0.0
 */
class Filter {
  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {
    return obj;
  }

  /**
   * Constructs a <code>Filter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Filter} obj Optional instance to populate.
   * @return {module:model/Filter} The populated <code>Filter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Filter();

      if (Object.prototype.hasOwnProperty.call(data, 'name')) {
        obj.name = ApiClient.convertToType(data.name, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'not')) {
        obj.not = ApiClient.convertToType(data.not, 'Boolean');
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      name: this.name,
      not: this.not,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>Filter</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Filter</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (!Filter.jsonStringValidation(data, 'name')) {
      throw new Error(
        `Expected the field \`name\` to be a primitive type in the JSON string but got ${data.name}`,
      );
    }

    return true;
  }

  /**
   * Returns name of the filter
   * @return {String}
   */
  getName() {
    return this.name;
  }

  /**
   * Sets name of the filter
   * @param {String} name name of the filter
   */
  setName(name) {
    this.name = name;
  }

  /**
   * Returns if true, inverses the filter
   * @return {Boolean}
   */
  getNot() {
    return this.not;
  }

  /**
   * Sets if true, inverses the filter
   * @param {Boolean} not if true, inverses the filter
   */
  setNot(not) {
    this.not = not;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ApiClient.convertToType(123456, 'String');
  }
}

/**
 * name of the filter
 * @member {String} name
 */
Filter.prototype.name = undefined;

/**
 * if true, inverses the filter
 * @member {Boolean} not
 * @default false
 */
Filter.prototype.not = false;

export default Filter;
