/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
/**
 * Enum class RelationType.
 * @enum {}
 * @readonly
 */
export default class RelationType {
  /**
   * value: "CONTAINED_BY"
   * @const
   */
  CONTAINED_BY = 'CONTAINED_BY';

  /**
   * value: "CONTAINS"
   * @const
   */
  CONTAINS = 'CONTAINS';

  /**
   * value: "RELATED_TO"
   * @const
   */
  RELATED_TO = 'RELATED_TO';

  /**
   * value: "RELATED_BY"
   * @const
   */
  RELATED_BY = 'RELATED_BY';

  /**
   * Returns a <code>RelationType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/RelationType} The enum <code>RelationType</code> value.
   */
  static constructFromObject(object) {
    return object;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ApiClient.convertToType(123456, 'String');
  }
}
