/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import ContextType from './ContextType.js';
import RelationType from './RelationType.js';

/**
 * The Relation model module.
 * @module model/Relation
 * @version 1.0.0
 */
class Relation {
  /**
   * Constructs a new <code>Relation</code>.
   * a relation to a context
   * @alias module:model/Relation
   * @param relationType {module:model/RelationType}
   * @param related {module:model/ContextType}
   */
  constructor(relationType, related) {
    Relation.initialize(this, relationType, related);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, relationType, related) {
    obj.relationType = relationType;
    obj.related = related;
  }

  /**
   * Constructs a <code>Relation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Relation} obj Optional instance to populate.
   * @return {module:model/Relation} The populated <code>Relation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Relation();

      if (Object.prototype.hasOwnProperty.call(data, 'relationType')) {
        obj.relationType = RelationType.constructFromObject(data.relationType);
      }
      if (Object.prototype.hasOwnProperty.call(data, 'related')) {
        obj.related = ContextType.constructFromObject(data.related);
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      relationType: this.relationType,
      related: this.related,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>Relation</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Relation</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of Relation.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          `The required field \`${property}\` is not found in the JSON data: ${JSON.stringify(
            data,
          )}`,
        );
      }
    }
    // validate the optional field `related`
    if (data.related) {
      // data not null
      ContextType.validateJSON(data.related);
    }

    return true;
  }

  /**
   * @return {module:model/RelationType}
   */
  getRelationType() {
    return this.relationType;
  }

  /**
   * @param {module:model/RelationType} relationType
   */
  setRelationType(relationType) {
    this.relationType = relationType;
  }

  /**
   * @return {module:model/ContextType}
   */
  getRelated() {
    return this.related;
  }

  /**
   * @param {module:model/ContextType} related
   */
  setRelated(related) {
    this.related = related;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ApiClient.convertToType(123456, 'String');
  }
}

Relation.RequiredProperties = ['relationType', 'related'];

/**
 * @member {module:model/RelationType} relationType
 */
Relation.prototype.relationType = undefined;

/**
 * @member {module:model/ContextType} related
 */
Relation.prototype.related = undefined;

export default Relation;
