/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import Context from './Context.js';
import Metric from './Metric.js';

/**
 * The SearchMetricsByQuery200ResponseResultsInner model module.
 * @module model/SearchMetricsByQuery200ResponseResultsInner
 * @version 1.0.0
 */
class SearchMetricsByQuery200ResponseResultsInner {
  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {
    return obj;
  }

  /**
   * Constructs a <code>SearchMetricsByQuery200ResponseResultsInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchMetricsByQuery200ResponseResultsInner} obj Optional instance to populate.
   * @return {module:model/SearchMetricsByQuery200ResponseResultsInner} The populated <code>SearchMetricsByQuery200ResponseResultsInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchMetricsByQuery200ResponseResultsInner();

      if (Object.prototype.hasOwnProperty.call(data, 'context')) {
        obj.context = Context.constructFromObject(data.context);
      }
      if (Object.prototype.hasOwnProperty.call(data, 'metrics')) {
        obj.metrics = ApiClient.convertToType(data.metrics, [Metric]);
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      context: this.context,
      metrics: this.metrics,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>SearchMetricsByQuery200ResponseResultsInner</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchMetricsByQuery200ResponseResultsInner</code>.
   */
  static validateJSON(data) {
    // validate the optional field `context`
    if (data.context) {
      // data not null
      Context.validateJSON(data.context);
    }
    if (data.metrics) {
      // data not null
      // ensure the json data is an array
      if (!Array.isArray(data.metrics)) {
        throw new Error(
          `Expected the field \`metrics\` to be an array in the JSON data but got ${data.metrics}`,
        );
      }
      // validate the optional field `metrics` (array)
      for (const item of data.metrics) {
        Metric.validateJSON(item);
      }
    }

    return true;
  }

  /**
   * @return {module:model/Context}
   */
  getContext() {
    return this.context;
  }

  /**
   * @param {module:model/Context} context
   */
  setContext(context) {
    this.context = context;
  }

  /**
   * @return {Array.<module:model/Metric>}
   */
  getMetrics() {
    return this.metrics;
  }

  /**
   * @param {Array.<module:model/Metric>} metrics
   */
  setMetrics(metrics) {
    this.metrics = metrics;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ApiClient.convertToType(123456, 'String');
  }
}

/**
 * @member {module:model/Context} context
 */
SearchMetricsByQuery200ResponseResultsInner.prototype.context = undefined;

/**
 * @member {Array.<module:model/Metric>} metrics
 */
SearchMetricsByQuery200ResponseResultsInner.prototype.metrics = undefined;

export default SearchMetricsByQuery200ResponseResultsInner;
