/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The UiConfigLogging model module.
 * @module model/UiConfigLogging
 * @version 1.0.0
 */
class UiConfigLogging {
  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {
    return obj;
  }

  /**
   * Constructs a <code>UiConfigLogging</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UiConfigLogging} obj Optional instance to populate.
   * @return {module:model/UiConfigLogging} The populated <code>UiConfigLogging</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UiConfigLogging();

      if (Object.prototype.hasOwnProperty.call(data, 'logLevel')) {
        obj.logLevel = ApiClient.convertToType(data.logLevel, 'String');
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      logLevel: this.logLevel,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>UiConfigLogging</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UiConfigLogging</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (!UiConfigLogging.jsonStringValidation(data, 'logLevel')) {
      throw new Error(
        `Expected the field \`logLevel\` to be a primitive type in the JSON string but got ${data.logLevel}`,
      );
    }

    return true;
  }

  /**
   * Returns Full name of an UI entity. Well-known name defined during development time
   * @return {module:model/UiConfigLogging.LogLevelEnum}
   */
  getLogLevel() {
    return this.logLevel;
  }

  /**
   * Sets Full name of an UI entity. Well-known name defined during development time
   * @param {module:model/UiConfigLogging.LogLevelEnum} logLevel Full name of an UI entity. Well-known name defined during development time
   */
  setLogLevel(logLevel) {
    this.logLevel = logLevel;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ApiClient.convertToType(123456, 'String');
  }
}

/**
 * Full name of an UI entity. Well-known name defined during development time
 * @member {module:model/UiConfigLogging.LogLevelEnum} logLevel
 */
UiConfigLogging.prototype.logLevel = undefined;

/**
 * Allowed values for the <code>logLevel</code> property.
 * @enum {String}
 * @readonly
 */
UiConfigLogging.LogLevelEnum = {
  /**
   * value: "debug"
   * @const
   */
  debug: 'debug',

  /**
   * value: "info"
   * @const
   */
  info: 'info',

  /**
   * value: "warning"
   * @const
   */
  warning: 'warning',

  /**
   * value: "error"
   * @const
   */
  error: 'error',

  /**
   * value: "critical"
   * @const
   */
  critical: 'critical',
};

export default UiConfigLogging;
