/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import UiConfigRoutesInternal from './UiConfigRoutesInternal.js';
import UiConfigRoutesLogging from './UiConfigRoutesLogging.js';

/**
 * The UiConfigRoutes model module.
 * @module model/UiConfigRoutes
 * @version 1.0.0
 */
class UiConfigRoutes {
  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {
    return obj;
  }

  /**
   * Constructs a <code>UiConfigRoutes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UiConfigRoutes} obj Optional instance to populate.
   * @return {module:model/UiConfigRoutes} The populated <code>UiConfigRoutes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UiConfigRoutes();

      if (Object.prototype.hasOwnProperty.call(data, 'internal')) {
        obj.internal = UiConfigRoutesInternal.constructFromObject(data.internal);
      }
      if (Object.prototype.hasOwnProperty.call(data, 'logging')) {
        obj.logging = UiConfigRoutesLogging.constructFromObject(data.logging);
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      internal: this.internal,
      logging: this.logging,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>UiConfigRoutes</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UiConfigRoutes</code>.
   */
  static validateJSON(data) {
    // validate the optional field `internal`
    if (data.internal) {
      // data not null
      UiConfigRoutesInternal.validateJSON(data.internal);
    }
    // validate the optional field `logging`
    if (data.logging) {
      // data not null
      UiConfigRoutesLogging.validateJSON(data.logging);
    }

    return true;
  }

  /**
   * @return {module:model/UiConfigRoutesInternal}
   */
  getInternal() {
    return this.internal;
  }

  /**
   * @param {module:model/UiConfigRoutesInternal} internal
   */
  setInternal(internal) {
    this.internal = internal;
  }

  /**
   * @return {module:model/UiConfigRoutesLogging}
   */
  getLogging() {
    return this.logging;
  }

  /**
   * @param {module:model/UiConfigRoutesLogging} logging
   */
  setLogging(logging) {
    this.logging = logging;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ApiClient.convertToType(123456, 'String');
  }
}

/**
 * @member {module:model/UiConfigRoutesInternal} internal
 */
UiConfigRoutes.prototype.internal = undefined;

/**
 * @member {module:model/UiConfigRoutesLogging} logging
 */
UiConfigRoutes.prototype.logging = undefined;

export default UiConfigRoutes;
