global:
  security:
    tls:
      enabled: true

#NEED FOR TLS
eric-sec-sip-tls:
  enabled: true

eric-log-transformer:
  enabled: false
  config:
    adpJson:
      transformation:
        enabled: true
  searchengine:
    logplaneConfig:
      - field: "[facility]"
        value: "log audit"
        newLogplane: "eric-oss-network-assurance-search-auditlog"
  syslog:
    syslogLogplane: "eric-oss-network-assurance-search"
  service:
    endpoints:
      syslogIn:
        tls:
          enforced: required

eric-data-search-engine:
  data:
    storageAllocation: 1Gi
  persistence:
    storageClass: ""
  service:
    endpoints:
      rest:
        tls:
          verifyClientCertificate: optional

#NEED FOR TLS
eric-data-distributed-coordinator-ed:
  pods:
    dced:
      replicas: 1
  persistence:
    persistentVolumeClaim:
      storageClassName: ""

eric-sec-key-management:
  persistence:
    type: pvc
    pvc:
      storageClassName: ""

eric-pm-server:
  enabled: false
  rbac:
    appMonitoring:
      configFileCreate: true
      enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 1Gi
      storageClass: ""

help-center-mock-eea:
  enabled: false
  publicPath: help-center-mock-eea
  contextRoot: ui

help-center-mock-ecm:
  enabled: false
  publicPath: help-center-mock-ecm
  contextRoot: some-path

# IAM
eric-data-document-database-iam:
  enabled: false
  postgresDatabase: iam
  credentials:
    kubernetesSecretName: eric-eea-iam-pg-usersecrets

# Fault Handling Service
eric-data-document-database-fault-handling:
  enabled: false
  backend:
    dbname: eric-oss-network-assurance-search
  postgresDatabase: eric-oss-network-assurance-search
  credentials:
    kubernetesSecretName: eric-eea-iam-pg-usersecrets

eric-sec-access-mgmt:
  enabled: false
  authenticationProxy:
    enabled: true
    lastlogintimeEnabled: true
    cookieDomain: nip.io
    logoutpageEnabled: true
    ingress:
      enabled: true
      hostname: # authn.iam.ci.eric-oss-network-assurance-search.<iccr-lb-ip-address>.nip.io
      existingTlsSecret: eric-oss-network-assurance-search-ingress-external-server-cert
      ingressClass: EEA-Applications
      caCertificateSecret: eric-eea-ingress-ctrl-common-client-ca
  ingress:
    enabled: true
    hostname: # iam.ci.eric-oss-network-assurance-search.<iccr-lb-ip-address>.nip.io
    ingressClass: EEA-Applications
    caCertificateSecret: eric-eea-ingress-ctrl-common-client-ca
    tls:
      enabled: true
      passthrough: false
      existingSecret: eric-oss-network-assurance-search-ingress-external-server-cert
  statefulset:
    adminSecret: eric-eea-iam-pg-usersecrets
  persistence:
    dbsecret: eric-eea-iam-pg-usersecrets
    dbUserkey: custom-user
    dbPasswdkey: custom-pwd
    dbName: iam
    dbHost: eric-data-document-database-iam
  service:
    endpoints:
      iam:
        tls:
          verifyClientCertificate: optional
      authenticationproxy:
        tls:
          verifyClientCertificate: optional
  tls:
    client:
      pg:
        issuer: eric-data-document-database-iam-client-ca

eric-fh-alarm-handler:
  enabled: false
  kafka:
    tlsport: 9093
  service:
    endpoints:
      restapi:
        tls:
          enforced: required
          verifyClientCertificate: optional
  alarmhandler:
    configmap:
      faultmappings: eric-oss-network-assurance-search-faultmappings-configmap
  credentials:
    kubernetesSecretName: eric-eea-iam-pg-usersecrets
  backend:
    dbname: eric-oss-network-assurance-search
    hostname: eric-data-document-database-fault-handling
  imageCredentials:
    eric-fh-alarm-handler:
      registry:
        url: selndocker.mo.sw.ericsson.se
    eric-fh-alarm-handler-rest:
      registry:
        url: selndocker.mo.sw.ericsson.se
    topic-creator:
      registry:
        url: selndocker.mo.sw.ericsson.se

eric-data-message-bus-kf:
  enabled: false
  tls:
    verifyServerCert: true
    sendClientCert: true
  service:
    endpoints:
      messagebuskf:
        tls:
          enforced: required

eric-eea-ingress-ctrl-applications:
  enabled: true
  fullnameOverride: eric-eea-ingress-ctrl-applications
  rbac:
    create: true
  service:
    externalTrafficPolicy: Local
    annotations:
      sharedVIPLabel: null
      addressPoolName: applications-pool
      cloudProviderLB: null
  ingressClass: EEA-Applications
  clientCertificate:
    enabled: true
    secret: eric-eea-ingress-ctrl-applications-internal-client-cert
  annotations:
    prometheus.io/scheme: HTTP
  resources:
    contour:
      limits:
        cpu: 150m # 75m delivered by ms
