/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
/* eslint-disable no-unused-vars */
import Error from '../model/Error.js';
import GetSystemState200Response from '../model/GetSystemState200Response.js';
/* eslint-enable no-unused-vars */

/**
 * System service.
 * @module api/SystemApi
 * @version 1.0.0
 */
export default class SystemApi {
  /* eslint-disable sonarjs/no-duplicate-string */

  /**
   * Constructs a new SystemApi.
   * @alias module:api/SystemApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Get operational state of NAS
   * Returns the operational state of the NAS.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetSystemState200Response} and HTTP response
   */
  getSystemStateWithHttpInfo() {
    const postBody = null;

    const pathParams = {};
    const queryParams = {};
    const headerParams = {};
    const formParams = {};

    const authNames = [];
    const contentTypes = [];
    const accepts = ['application/json'];
    const returnType = GetSystemState200Response;
    return this.apiClient.callApi(
      '/system/state',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
    );
  }

  /**
   * Get operational state of NAS
   * Returns the operational state of the NAS.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetSystemState200Response}
   */
  getSystemState() {
    return this.getSystemStateWithHttpInfo().then((responseAndData) => responseAndData.data);
  }

  /* eslint-enable sonarjs/no-duplicate-string */
}
