version: '3.0'

services:
  openapi_mock:
    container_name: indexer_mock
    image: muonsoft/openapi-mock
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: /spec/openapi.yaml
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /spec
