version: '2.1'
services:
  seleniumhub:
    container_name: docker_frontend_seleniumhub_${BUILD_TAG}
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/selenium/hub:3.141.59-20210929 # update this regularly
    shm_size: 1g

  nodechrome:
    container_name: docker_frontend_nodechrome_${BUILD_TAG}
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/selenium/node-chrome:3.141.59-20210929 # update this regularly
    links:
      - seleniumhub:hub
    depends_on:
      - seleniumhub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    volumes:
      - ../:/local/app
    shm_size: 2g

    # it can be only started on a repository which has been initalized via npm install* command
  mock-server:
    container_name: docker_frontend_mock-server_${BUILD_TAG}
    image: armdocker.rnd.ericsson.se/proj-adp-cicd-drop/adp-nodejs-lts-builder-image:20.10.0-0
    command: bash -c "cd /local/app && npm run start:frontend"
    volumes:
      - ../:/local/app
    environment:
      - TEST_MODE=mock
    shm_size: 1g
    user: node

    # it can be only started on a repository which has been initalized via npm install* command
  test-mock:
    container_name: docker_frontend_test-mock_${BUILD_TAG}
    image: armdocker.rnd.ericsson.se/proj-adp-cicd-drop/adp-nodejs-lts-builder-image:20.10.0-0
    command: >
      bash -c "
      npx wait-on --log -i 2000 -t 600000 http-get://seleniumhub:4444 http://mock-server:8080 &&
      cd /local/app &&
      npm run e2e:frontend:docker ;
      TEST_STATUS=$$? ;
      npm run e2e:frontend:generateReport ;
      exit $$TEST_STATUS"
    links:
      - seleniumhub
      - mock-server
    depends_on:
      - nodechrome
      - mock-server
    environment:
      - BASE_URL=http://mock-server:8080
      - SELENIUM_HOST=seleniumhub
      - SELENIUM_PORT=4444
      - DOWNLOAD_DIRECTORY_PATH=${DOWNLOAD_PATH}
      - TEST_MODE=mock
      - MOCK_SERVER_URL=http://mock-server:8080
    volumes:
      - ../:/local/app
    shm_size: 1g
    user: node
