/* eslint-disable sonarjs/no-duplicate-string */
export const constants = {
  CHILDREN_WAIT_TIMEOUT: 7_500,
  ROOT_WAIT_TIMEOUT: 10_000,
  NEXT_TICK_WAIT_TIMEOUT: 800,
  TABLE_SETTINGS: { autoRefresh: false, columns: [], rowHeight: 'compact' },
  MOCK_TABLE_DATA: [
    {
      col1: { value: 'Item 1', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { value: 'Details 1', beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 1', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 1', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
    {
      col1: { value: 'Item 2', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { value: 'Details 2', beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 2', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 2', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
    {
      col1: { value: 'Item 3', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { value: 'Details 3', beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 3', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 3', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
    {
      col1: { value: 'Item 4', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { value: 'Details 4', beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 4', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 4', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
    {
      col1: { value: 'Item 5', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { value: 'Details 5', beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 5', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 5', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
    {
      col1: { value: 'Item 6', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { value: 'Details 6', beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 6', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 6', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
    {
      col1: { value: 'Item 7', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { value: 'Details 7', beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 7', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 7', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
    {
      col1: { value: 'Item 8', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { value: 'Details 8', beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 8', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 8', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
    {
      col1: { value: 'Item 9', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { value: 'Details 9', beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 9', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 9', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
    {
      col1: { value: '', beginTimestamp: undefined, endTimestamp: undefined },
      col2: { beginTimestamp: 1513520073, endTimestamp: undefined },
      col3: { value: 'Details 10', beginTimestamp: undefined, endTimestamp: 1513520073 },
      col4: { value: 'Details 10', beginTimestamp: 1513520073, endTimestamp: 1513540073 },
    },
  ],
  MOCK_TABLE_COLUMNS: [
    {
      title: 'Title 1',
      attribute: 'col1',
      sortable: true,
      sortNotificationInfo: 'col1',
    },
    {
      title: 'Title 2',
      attribute: 'col2',
      sortable: true,
      sortNotificationInfo: 'col2',
    },
    {
      title: 'Title 3',
      attribute: 'col3',
      sortable: true,
      sortNotificationInfo: 'col3',
    },
    {
      title: 'Title 4',
      attribute: 'col4',
      sortable: true,
      sortNotificationInfo: 'col4',
    },
  ],
  MOCK_TABLE_ACTIONS: [
    {
      label: 'Open site for NSI',
      data: {
        operation: 'open-tab',
        context: { id: 'CID_1234', contextFields: 'Array(2)', name: 'NSSAI & NSI Context' },
      },
      facetCounts: {},
    },
    {
      label: 'Open supporting NSI',
      data: {
        operation: 'open-tab',
        context: { id: 'CID_1235', contextFields: 'Array(2)', name: 'NSSAI & NSI Context' },
      },
      facetCounts: {},
    },
    {
      label: 'View Network Assurance Dashboard',
      data: {
        operation: 'open-tab',
        context: { id: 'CID_1236', contextFields: 'Array(2)', name: 'NSSAI & NSI Context' },
      },
      facetCounts: {},
    },
    {
      label: 'view KPIs for NSSAI & NSI',
      data: {
        operation: 'open-tab',
        context: { id: 'CID_1237', contextFields: 'Array(2)', name: 'NSSAI & NSI Context' },
      },
      facetCounts: {},
    },
    {
      label: 'Use KPIs for NSSAI & NSI',
      data: {
        operation: 'open-tab',
        context: { id: 'CID_1238', contextFields: ' Array(2)', name: 'NSSAI & NSI Context' },
      },
      facetCounts: {},
    },
    {
      label: 'Use Network Assurance Dashboard',
      data: {
        operation: 'open-tab',
        context: { id: 'CID_1239', contextFields: 'Array(2)', name: 'NSSAI & NSI Context' },
      },
      facetCounts: {},
    },
  ],
  MOCK_METRIC_CATEGORY_PICKER_DATA: {
    viewAllSelected: false,
    maxPillCount: 10,
  },
  KEYDOWN_EVENTS: {
    ENTER: new KeyboardEvent('keydown', {
      code: 'Enter',
      key: 'Enter',
      charCode: 13,
      keyCode: 13,
      view: window,
      bubbles: true,
    }),
    SPACE: new KeyboardEvent('keydown', {
      code: 'Space',
      key: 'Space',
      charCode: 32,
      keyCode: 32,
      view: window,
      bubbles: true,
    }),
    TAB: new KeyboardEvent('keydown', {
      code: 'Tab',
      key: 'Tab',
      charCode: 9,
      keyCode: 9,
      view: window,
      bubbles: true,
    }),
    ESCAPE: new KeyboardEvent('keydown', {
      code: 'Escape',
      key: 'Escape',
      charCode: 27,
      keyCode: 27,
      view: window,
      bubbles: true,
    }),
    ARROW_UP: new KeyboardEvent('keydown', {
      code: 'ArrowUp',
      key: 'ArrowUp',
      charCode: 38,
      keyCode: 38,
      view: window,
      bubbles: true,
    }),
    ARROW_DOWN: new KeyboardEvent('keydown', {
      code: 'ArrowDown',
      key: 'ArrowDown',
      charCode: 40,
      keyCode: 40,
      view: window,
      bubbles: true,
    }),
    HOME: new KeyboardEvent('keydown', {
      code: 'Home',
      key: 'Home',
      charCode: 36,
      keyCode: 36,
      view: window,
      bubbles: true,
    }),
    END: new KeyboardEvent('keydown', {
      code: 'End',
      key: 'End',
      charCode: 35,
      keyCode: 35,
      view: window,
      bubbles: true,
    }),
    PAGE_UP: new KeyboardEvent('keydown', {
      code: 'PageUp',
      key: 'PageUp',
      charCode: 33,
      keyCode: 33,
      view: window,
      bubbles: true,
    }),
    PAGE_DOWN: new KeyboardEvent('keydown', {
      code: 'PageDown',
      key: 'PageDown',
      charCode: 34,
      keyCode: 34,
      view: window,
      bubbles: true,
    }),
  },
};
