{{- if (index .Values "eric-eea-ingress-ctrl-applications" "enabled") }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalUserCA
metadata:
  name: ingress-ctrl-common-client-ca
spec:
  kubernetes:
    generatedSecretName: eric-eea-ingress-ctrl-common-client-ca
  certificate:
    subject:
      cn: eric-eea-ingress-ctrl-common-client-ca
{{- end }}
