{{- $global := fromJson (include "ci.global" .) -}}
{{- if $global.security.tls.enabled }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: eric-oss-network-assurance-search-ingress-external-server-cert
  labels:
  annotations:
spec:
  kubernetes:
    generatedSecretName: eric-oss-network-assurance-search-ingress-external-server-cert
    secretType: tls
  certificate:
    subject:
      cn: eric-oss-network-assurance-search-ingress-host-name
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: true
    validity:
      overrideTtl: 2592000 # 30 days in seconds
{{- end }}
