export default {
  LAUNCHER: 'launcher',
  PRODUCT_TYPE: 'product',
  CATEGORY_TYPE: 'category',
  EXTERNAL_TYPE: 'external',
  EUISDK_TYPE: 'euisdk',
  LAST_OPENED: 'lastOpened',
  IS_FAVORITE: 'isFavorite',
  ALL_APPS: 'all',
  LANDING_CARD_COUNT: 8,
  COLLAPSED_CARD_COUNT: 4,
  SHOW_FAVORITES_ONLY: 'favorites',
  PRODUCT_NAME: 'productName',
  NAME_RANK: 5,
  TAGS_RANK: 3,
  SECONDARY_INFO_RANK: 2,
  DESC_RANK: 1,
  ENTER_KEY: 'Enter',
  ESCAPE_KEY: 'Escape',
  SPACE_KEY: ' ',
  F_KEY: 'f',
  I_KEY: 'i',
  FAVORITE_STATE: {
    FAVORITE: 'favorite',
    NOT_FAVORITE: 'not-favorite',
    PARTIALLY_FAVORITE: 'partially-favorite',
  },
  FAVORITE_COLOR: 'var(--yellow-43)',
  COMPACT_VIEW_BREAKPOINT: 680,
  TABLE_COLUMN_BUFFER_WIDTH: 36,
  MIN_COLUMN_WIDTH: 150,
  LOCAL_STORAGE_CHANGE: 'localStorageChange',
  FOCUS_SEARCH_BAR_EVENT: 'focus:searchBar',
  VIEW_TYPE: {
    TILE: 'tile',
    LIST: 'list',
  },
  GROUPPING_TYPE: {
    CATEGORY: 'category',
    ALPHABETICAL: 'alphabetical',
  },
  OPERATIONS: {
    EQUAL: 'eq',
    LESS_THAN_EQUAL: 'lte',
    GREATER_THAN_EQUAL: 'gte',
    NOT_EQUAL: 'neq',
    IN_RANGE: 'inr',
    NOT_IN_RANGE: 'ninr',
  },
  CONFIG_LOCATION: '/deployment-config/frontend-config.json',
  FRONTEND_CONFIG_NAME: 'frontendConfig',
  HISTORICAL_DASHBOARD_NAMESPACE: 'eric-cnom-server',
  SYSTEM_STATUS: {
    INITIALIZING: 'initializing',
    READY: 'ready',
    ERROR: 'error',
  },
  PERSISTENCE_ENGINE_OS: 'os',
  DISCOVERY_OS: 'ais',
};
