/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ModelUtil from '../utils/ModelUtil.js';
/* eslint-disable no-unused-vars */
import ContextType from './ContextType.js';
/* eslint-enable no-unused-vars */

/**
 * The ContextFacet model module.
 * @module model/ContextFacet
 * @version 1.0.0
 */
class ContextFacet {
  /**
   * Constructs a new <code>ContextFacet</code>.
   * a relation to a context
   * @alias module:model/ContextFacet
   * @param contextType {module:model/ContextType}
   * @param count {Number} count for a context type
   */
  constructor(contextType, count) {
    ContextFacet.initialize(this, contextType, count);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, contextType, count) {
    obj.contextType = contextType;
    obj.count = count;
  }

  /**
   * Constructs a <code>ContextFacet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContextFacet} obj Optional instance to populate.
   * @return {module:model/ContextFacet} The populated <code>ContextFacet</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContextFacet();

      if (Object.prototype.hasOwnProperty.call(data, 'contextType')) {
        obj.contextType = ModelUtil.convertToType(data.contextType, 'ContextType');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'count')) {
        obj.count = ModelUtil.convertToType(data.count, 'Number');
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      contextType: this.contextType,
      count: this.count,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>ContextFacet</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContextFacet</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of ContextFacet.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          JSON.stringify({
            customValidationError: true,
            name: 'ModelValidationError',
            message: `The required field \`${property}\` is not found in the JSON data: ${JSON.stringify(
              data,
            )}`,
          }),
        );
      }
    }
    // validate the optional field `contextType`
    if (data.contextType) {
      // data not null
      ContextType.validateJSON(data.contextType);
    }

    return true;
  }

  /**
   * @return {module:model/ContextType}
   */
  getContextType() {
    return this.contextType;
  }

  /**
   * @param {module:model/ContextType} contextType
   */
  setContextType(contextType) {
    this.contextType = contextType;
  }

  /**
   * Returns count for a context type
   * @return {Number}
   */
  getCount() {
    return this.count;
  }

  /**
   * Sets count for a context type
   * @param {Number} count count for a context type
   */
  setCount(count) {
    this.count = count;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ModelUtil.convertToType(123456, 'String');
  }
}

ContextFacet.RequiredProperties = ['contextType', 'count'];

/**
 * @member {module:model/ContextType} contextType
 */
ContextFacet.prototype.contextType = undefined;

/**
 * count for a context type
 * @member {Number} count
 */
ContextFacet.prototype.count = undefined;

export default ContextFacet;
