/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ModelUtil from '../utils/ModelUtil.js';
/* eslint-disable no-unused-vars */
import EntityType from './EntityType.js';
/* eslint-enable no-unused-vars */

/**
 * The ContextType model module.
 * @module model/ContextType
 * @version 1.0.0
 */
class ContextType {
  /**
   * Constructs a new <code>ContextType</code>.
   * context type
   * @alias module:model/ContextType
   * @param id {String} an unique identifier of the context type
   * @param contextFields {Array.<module:model/EntityType>} aggregated entities
   */
  constructor(id, contextFields) {
    ContextType.initialize(this, id, contextFields);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, id, contextFields) {
    obj.id = id;
    obj.contextFields = contextFields;
  }

  /**
   * Constructs a <code>ContextType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContextType} obj Optional instance to populate.
   * @return {module:model/ContextType} The populated <code>ContextType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContextType();

      if (Object.prototype.hasOwnProperty.call(data, 'id')) {
        obj.id = ModelUtil.convertToType(data.id, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'name')) {
        obj.name = ModelUtil.convertToType(data.name, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'description')) {
        obj.description = ModelUtil.convertToType(data.description, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'contextFields')) {
        obj.contextFields = ModelUtil.convertToType(data.contextFields, [EntityType]);
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      id: this.id,
      name: this.name,
      description: this.description,
      contextFields: this.contextFields,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>ContextType</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContextType</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of ContextType.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          JSON.stringify({
            customValidationError: true,
            name: 'ModelValidationError',
            message: `The required field \`${property}\` is not found in the JSON data: ${JSON.stringify(
              data,
            )}`,
          }),
        );
      }
    }
    // ensure the json data is a string
    if (!ContextType.jsonStringValidation(data, 'id')) {
      throw new Error(
        JSON.stringify({
          customValidationError: true,
          name: 'ModelValidationError',
          message: `Expected the field \`id\` to be a primitive type in the JSON string but got ${data.id}`,
        }),
      );
    }
    // ensure the json data is a string
    if (!ContextType.jsonStringValidation(data, 'name')) {
      throw new Error(
        JSON.stringify({
          customValidationError: true,
          name: 'ModelValidationError',
          message: `Expected the field \`name\` to be a primitive type in the JSON string but got ${data.name}`,
        }),
      );
    }
    // ensure the json data is a string
    if (!ContextType.jsonStringValidation(data, 'description')) {
      throw new Error(
        JSON.stringify({
          customValidationError: true,
          name: 'ModelValidationError',
          message: `Expected the field \`description\` to be a primitive type in the JSON string but got ${data.description}`,
        }),
      );
    }
    if (data.contextFields) {
      // data not null
      // ensure the json data is an array
      if (!Array.isArray(data.contextFields)) {
        throw new Error(
          JSON.stringify({
            customValidationError: true,
            name: 'ModelValidationError',
            message: `Expected the field \`contextFields\` to be an array in the JSON data but got ${data.contextFields}`,
          }),
        );
      }
      // validate the optional field `contextFields` (array)
      for (const item of data.contextFields) {
        EntityType.validateJSON(item);
      }
    }

    return true;
  }

  /**
   * Returns an unique identifier of the context type
   * @return {String}
   */
  getId() {
    return this.id;
  }

  /**
   * Sets an unique identifier of the context type
   * @param {String} id an unique identifier of the context type
   */
  setId(id) {
    this.id = id;
  }

  /**
   * Returns a display name of the context
   * @return {String}
   */
  getName() {
    return this.name;
  }

  /**
   * Sets a display name of the context
   * @param {String} name a display name of the context
   */
  setName(name) {
    this.name = name;
  }

  /**
   * Returns a description of the context
   * @return {String}
   */
  getDescription() {
    return this.description;
  }

  /**
   * Sets a description of the context
   * @param {String} description a description of the context
   */
  setDescription(description) {
    this.description = description;
  }

  /**
   * Returns aggregated entities
   * @return {Array.<module:model/EntityType>}
   */
  getContextFields() {
    return this.contextFields;
  }

  /**
   * Sets aggregated entities
   * @param {Array.<module:model/EntityType>} contextFields aggregated entities
   */
  setContextFields(contextFields) {
    this.contextFields = contextFields;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ModelUtil.convertToType(123456, 'String');
  }
}

ContextType.RequiredProperties = ['id', 'contextFields'];

/**
 * an unique identifier of the context type
 * @member {String} id
 */
ContextType.prototype.id = undefined;

/**
 * a display name of the context
 * @member {String} name
 */
ContextType.prototype.name = undefined;

/**
 * a description of the context
 * @member {String} description
 */
ContextType.prototype.description = undefined;

/**
 * aggregated entities
 * @member {Array.<module:model/EntityType>} contextFields
 */
ContextType.prototype.contextFields = undefined;

export default ContextType;
