/**
 * Assurance Search API
 * ```   Ericsson   |   DocNo n/155 19-CAF CAF 101 105/3   |   Rev PA1   |   Inter-work Description ``` ## Introduction This document describes the User Interface Internal REST API identified in the ADP GUI FA. ### Terms - **UI Internal Interface**: The interface providing access to static content meant to be used exclusively by the User Interface itself. All static content paths are relative to this URI. - **Client Container**: An SPA (Single Page Application) implementing the App Shell pattern e.g. E-UI SDK Container. - **UI App**: A full screen user interface exposed by a Microservice that can execute in the Client Container e.g. E-UI SDK App. - ***External UI App***: Any UIs that have a separate web page (outside the Client Container) or other alternative renderer e.g. Citrix. - **UI Component**: A reusable, embeddable UI Web Component exposed by a Microservice e.g. E-UI SDK Shareable Components.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sasha.katsman@ericsson.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ModelUtil from '../utils/ModelUtil.js';
/* eslint-disable no-unused-vars */
/* eslint-enable no-unused-vars */

/**
 * The Family model module.
 * @module model/Family
 * @version 1.0.0
 */
class Family {
  /**
   * Constructs a new <code>Family</code>.
   * metric family
   * @alias module:model/Family
   * @param name {String} metric family name
   * @param widget {String} metric category widget which is displayed within the historical dashboard family's tab
   */
  constructor(name, widget) {
    Family.initialize(this, name, widget);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, name, widget) {
    obj.name = name;
    obj.widget = widget;
  }

  /**
   * Constructs a <code>Family</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Family} obj Optional instance to populate.
   * @return {module:model/Family} The populated <code>Family</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Family();

      if (Object.prototype.hasOwnProperty.call(data, 'name')) {
        obj.name = ModelUtil.convertToType(data.name, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'title')) {
        obj.title = ModelUtil.convertToType(data.title, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'subtitle')) {
        obj.subtitle = ModelUtil.convertToType(data.subtitle, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'unit')) {
        obj.unit = ModelUtil.convertToType(data.unit, 'String');
      }
      if (Object.prototype.hasOwnProperty.call(data, 'widget')) {
        obj.widget = ModelUtil.convertToType(data.widget, 'String');
      }
    }
    return obj;
  }

  convertToObject() {
    return {
      name: this.name,
      title: this.title,
      subtitle: this.subtitle,
      unit: this.unit,
      widget: this.widget,
    };
  }

  static jsonStringValidation(data, keyName) {
    if (data[keyName] && !(typeof data[keyName] === 'string' || data[keyName] instanceof String)) {
      return false;
    }
    return true;
  }

  /**
   * Validates the JSON data with respect to <code>Family</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Family</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of Family.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          JSON.stringify({
            customValidationError: true,
            name: 'ModelValidationError',
            message: `The required field \`${property}\` is not found in the JSON data: ${JSON.stringify(
              data,
            )}`,
          }),
        );
      }
    }
    // ensure the json data is a string
    if (!Family.jsonStringValidation(data, 'name')) {
      throw new Error(
        JSON.stringify({
          customValidationError: true,
          name: 'ModelValidationError',
          message: `Expected the field \`name\` to be a primitive type in the JSON string but got ${data.name}`,
        }),
      );
    }
    // ensure the json data is a string
    if (!Family.jsonStringValidation(data, 'title')) {
      throw new Error(
        JSON.stringify({
          customValidationError: true,
          name: 'ModelValidationError',
          message: `Expected the field \`title\` to be a primitive type in the JSON string but got ${data.title}`,
        }),
      );
    }
    // ensure the json data is a string
    if (!Family.jsonStringValidation(data, 'subtitle')) {
      throw new Error(
        JSON.stringify({
          customValidationError: true,
          name: 'ModelValidationError',
          message: `Expected the field \`subtitle\` to be a primitive type in the JSON string but got ${data.subtitle}`,
        }),
      );
    }
    // ensure the json data is a string
    if (!Family.jsonStringValidation(data, 'unit')) {
      throw new Error(
        JSON.stringify({
          customValidationError: true,
          name: 'ModelValidationError',
          message: `Expected the field \`unit\` to be a primitive type in the JSON string but got ${data.unit}`,
        }),
      );
    }
    // ensure the json data is a string
    if (!Family.jsonStringValidation(data, 'widget')) {
      throw new Error(
        JSON.stringify({
          customValidationError: true,
          name: 'ModelValidationError',
          message: `Expected the field \`widget\` to be a primitive type in the JSON string but got ${data.widget}`,
        }),
      );
    }

    return true;
  }

  /**
   * Returns metric family name
   * @return {String}
   */
  getName() {
    return this.name;
  }

  /**
   * Sets metric family name
   * @param {String} name metric family name
   */
  setName(name) {
    this.name = name;
  }

  /**
   * Returns metric family title
   * @return {String}
   */
  getTitle() {
    return this.title;
  }

  /**
   * Sets metric family title
   * @param {String} title metric family title
   */
  setTitle(title) {
    this.title = title;
  }

  /**
   * Returns metric family subtitle
   * @return {String}
   */
  getSubtitle() {
    return this.subtitle;
  }

  /**
   * Sets metric family subtitle
   * @param {String} subtitle metric family subtitle
   */
  setSubtitle(subtitle) {
    this.subtitle = subtitle;
  }

  /**
   * Returns metric family units
   * @return {String}
   */
  getUnit() {
    return this.unit;
  }

  /**
   * Sets metric family units
   * @param {String} unit metric family units
   */
  setUnit(unit) {
    this.unit = unit;
  }

  /**
   * Returns metric category widget which is displayed within the historical dashboard family's tab
   * @return {String}
   */
  getWidget() {
    return this.widget;
  }

  /**
   * Sets metric category widget which is displayed within the historical dashboard family's tab
   * @param {String} widget metric category widget which is displayed within the historical dashboard family's tab
   */
  setWidget(widget) {
    this.widget = widget;
  }

  // Placeholder method to suppress eslint's no-unused-vars error
  static placeholder() {
    ModelUtil.convertToType(123456, 'String');
  }
}

Family.RequiredProperties = ['name', 'widget'];

/**
 * metric family name
 * @member {String} name
 */
Family.prototype.name = undefined;

/**
 * metric family title
 * @member {String} title
 */
Family.prototype.title = undefined;

/**
 * metric family subtitle
 * @member {String} subtitle
 */
Family.prototype.subtitle = undefined;

/**
 * metric family units
 * @member {String} unit
 */
Family.prototype.unit = undefined;

/**
 * metric category widget which is displayed within the historical dashboard family's tab
 * @member {String} widget
 */
Family.prototype.widget = undefined;

export default Family;
