documents:
  # Eridoc
  # - name: "API Documentation - Eridoc"
  #   external-link:
  #     Title: "{api-title}"
  #     Document_id: "{api-id}"
  #     Rev: "{api-rev}"
  # - name: "Service user guide - Eridoc"
  #   external-link:
  #     Title: "{user-guide-title}"
  #     Document_id: "{user-guide-id}"
  #     Rev: "{user-guide-rev}"
  # - name: "Software Vendor List (SVL)"
  #   filepath: build/doc-archive/svl.zip
  # - name: "Test Report"
  #   external-link:
  #     Title: "{test-report-title}"
  #     Document_id: "{test-report-id}"
  #     Rev: "{test-report-rev}"
  # - name: "Test Specification - Eridoc"
  #   external-link:
  #     Title: "{test-spec-title}"
  #     Document_id: "{test-spec-id}"
  #     Rev: "{test-spec-rev}"
  # - name: "Application Developers Guide - Eridoc"
  #   external-link:
  #     Title: "{dev-guide-title}"
  #     Document_id: "{dev-guide-id}"
  #     Rev: "{dev-guide-rev}"
  # - name: "Vulnerability Analysis Report"
  #   external-link:
  #     Title: "{vul-anal-title}"
  #     Document_id: "{vul-anal-id}"
  #     Rev: "{vul-anal-rev}"
  #   restricted: true
  # - name: "Product Revision Information (PRI)"
  #   external-link:
  #     Title: "{pri-title}"
  #     Document_id: "{pri-id}"
  #     Rev: "{pri-rev}"
  # - name: "Risk Assessment & Privacy Impact Assessment"
  #   external-link:
  #     Title: "{risk-assessment-title}"
  #     Document_id: "{risk-assessment-id}"
  #     Rev: "{risk-assessment-rev}"
  #   restricted: true
  # - name: "Secure coding report"
  #   external-link:
  #     Title: "{sec-coding-title}"
  #     Document_id: "{sec-coding-id}"
  #     Rev: "{sec-coding-rev}"
  #   restricted: true
  # HTML marketplace docs
  - name: "Service User Guide"
    filepath: build/doc-archive/html/service-user-guide.zip
    default: true
  - name: "Release Notes"
    filepath: build/doc-archive/html/release-notes.zip
  - name: "Contributing Guideline"
    filepath: build/doc-archive/html/contributing-guideline.zip
  - name: "Inner Source README"
    external-link: "https://gerrit-gamma.gic.ericsson.se/plugins/gitiles/OSS/com.ericsson.oss.air/eric-oss-network-assurance-search/+/master/README.md"
  - name: "API Documentation"
    filepath: build/doc-archive/html/api-documentation.zip
  - name: "Application Developers Guide"
    filepath: build/doc-archive/html/application-developers-guide.zip
  - name: "Test Specification"
    filepath: build/doc-archive/html/test-specification.zip
